numbers = set()

num1 = int(input("enter the number: "))
numbers.add(num1)
num2 = int(input("enter the number: "))
numbers.add(num2)
num3 = int(input("enter the number: "))
numbers.add(num3)
num4 = int(input("enter the number: "))
numbers.add(num4)
num5 = int(input("enter the number: "))
numbers.add(num5)
num6 = int(input("enter the number: "))
numbers.add(num6)
num7 = int(input("enter the number: "))
numbers.add(num7)
num8 = int(input("enter the number: "))
numbers.add(num8)

print("all unique numbers: ",numbers)
